In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style as style
import seaborn as sns
import os
from turtledemo.penrose import f
style.use('ggplot')

In [5]:
print("current working directory:", os.getcwd())

current working directory: c:\Users\Kaori Komata\DATA695\creditML\notebooks\0)PreProcess

In [6]:
# Load Train.csv into DataFrame
dataPath = '../../data/credit_card_transactions.csv'
df = pd.read_csv(dataPath)
df.head(20)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,28705.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,NaN
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,83236.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,NaN
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,22844.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1325376248,40.653382,-76.152667,0,17972.0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0,NaN
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1325376308,38.948089,-78.540296,0,22644.0
8,8,2019-01-01 00:05:18,4922710831011201,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0,15236.0
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0,42442.0
10,10,2019-01-01 00:06:23,4642894980163,fraud_Rutherford-Mertz,grocery_pos,24.74,Eddie,Mendez,M,1831 Faith View Suite 653,...,-95.0380,7297,IT trainer,1990-07-13,d71c95ab6b7356dd74389d41df429c87,1325376383,40.275891,-96.011548,0,68348.0
11,11,2019-01-01 00:06:53,377234009633447,fraud_Kerluke-Abshire,shopping_net,7.77,Theresa,Blackwell,F,43576 Kristina Islands,...,-77.8229,1925,Systems developer,1966-02-14,3c74776e558f1499a7824b556e474b1d,1325376413,40.103866,-78.624459,0,15554.0
12,12,2019-01-01 00:06:56,180042946491150,fraud_Lockman Ltd,grocery_pos,71.22,Charles,Robles,M,3337 Lisa Divide,...,-82.7243,341043,"Engineer, land",1989-02-28,c1d9a7ddb1e34639fe82758de97f4abf,1325376416,27.630593,-82.308891,0,33598.0
13,13,2019-01-01 00:07:27,5559857416065248,fraud_Kiehn Inc,grocery_pos,96.29,Jack,Hill,M,5916 Susan Bridge Apt. 939,...,-122.5258,589,Systems analyst,1945-12-21,413636e759663f264aae1819a4d4f231,1325376447,41.657520,-122.230347,0,NaN
14,14,2019-01-01 00:09:03,3514865930894695,fraud_Beier-Hyatt,shopping_pos,7.77,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,-105.8189,899,Naval architect,1967-08-30,8a6293af5ed278dea14448ded2685fea,1325376543,32.863258,-106.520205,0,NaN
15,15,2019-01-01 00:09:20,6011999606625827,fraud_Schmidt and Sons,shopping_net,3.26,Ronald,Carson,M,870 Rocha Drive,...,-73.9800,4664,"Radiographer, diagnostic",1965-06-30,baae0b096835c975857eea7e28dde3dc,1325376560,41.831174,-74.335559,0,12446.0
16,16,2019-01-01 00:10:49,6011860238257910,fraud_Lebsack and Sons,misc_net,327.00,Lisa,Mendez,F,44259 Beth Station Suite 215,...,-98.0727,1078,"Programme researcher, broadcasting/film/video",1952-07-06,991c04803b4d4eeab30d6245a872e3d3,1325376649,36.384092,-99.048472,0,73852.0
17,17,2019-01-01 00:10:58,3565423334076143,fraud_Mayert Group,shopping_pos,341.67,Nathan,Thomas,M,4923 Campbell Pines Suite 717,...,-87.3667,4081,Energy engineer,1938-03-15,f12cf52be2175703db789a4644c32f25,1325376658,38.674491,-88.305767,0,62824.0
18,18,2019-01-01 00:11:14,2348245054386329,"fraud_Konopelski, Schneider and Hartmann",food_dining,63.07,Justin,Gay,M,268 Hayes Rue Suite 811,...,-79.9416,2518,Event organiser,1946-02-02,8500f3d459047eac8443307b1e8296e5,1325376674,41.430274,-79.492553,0,16364.0
19,19,2019-01-01 00:12:34,4956828990005111019,"fraud_Schultz, Simonis and Little",grocery_pos,44.71,Kenneth,Robinson,M,269 Sanchez Rapids,...,-74.2239,124967,Operational researcher,1980-12-21,09eff9c806365e2a6be12c1bbab3d70e,1325376754,40.079588,-74.848087,0,8016.0

# DATA CLEANING CHECKLIST 

## Check for missing values

In [7]:
df.isnull().sum().sort_values(ascending=False)

merch_zipcode            195973
trans_date_trans_time         0
is_fraud                      0
merch_long                    0
merch_lat                     0
unix_time                     0
trans_num                     0
dob                           0
job                           0
city_pop                      0
long                          0
lat                           0
Unnamed: 0                    0
state                         0
city                          0
street                        0
gender                        0
last                          0
first                         0
amt                           0
category                      0
merchant                      0
cc_num                        0
zip                           0
dtype: int64

Dropping after the null chek <br>
mech_zipcode shows a lot of missing values so we need to drop it <br>
Unamed: 0 is just the row index <br>

In [8]:
drop_cols = ['Unnamed: 0', 'merch_zipcode']
df.drop(columns=drop_cols, inplace=True)
print("Dropped columns:", drop_cols)

Dropped columns: ['Unnamed: 0', 'merch_zipcode']

## Data Types Check

In [9]:
print(set(df.dtypes.to_list()),"\n")
df.info()

{dtype('O'), dtype('float64'), dtype('int64')}

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  object
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  object
 6   last                   1296675 non-null  object
 7   gender                 1296675 non-null  object
 8   street                 1296675 non-null  object
 9   city                   1296675 non-null  object
 10  state                  1296675 non-null  object
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  object
 16  dob                    1296675 non-null  object
 17  trans_num              1296675 non-null  object
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 217.6+ MB

## Data Description

In [10]:
df.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

## Duplicate Data

In [11]:
duplicates = df.duplicated().sum()
print(f"Number of duplicates: {duplicates}")

dup_count = df.duplicated().sum()
print(f"Duplicate rows: {dup_count}")
if dup_count > 0:
    df.drop_duplicates(inplace=True)
    print("Dropped duplicate rows")

Number of duplicates: 0
Duplicate rows: 0

## OUTLIER DETECTION

In [12]:
#  - Flag txns above 99th percentile
q99 = df['amt'].quantile(0.99)
#creating a new column where encoding -> where 1 indicates high value transaction outlier and 0 indicates normal transaction
df['amt_outlier'] = (df['amt'] > q99).astype(int)
#99% of all transactions are below this value which is $545.99 so only 1 % of transactions are higher than this
# might pass this encoding into a model to predict fraud (behaviour at large spending values)
print(f"99th percentile of amt = {q99:.2f}; flagged amt_outlier")

99th percentile of amt = 545.99; flagged amt_outlier

## CLASS BALANCE

In [13]:
fraud_rate = df['is_fraud'].mean()
print(f"Fraud rate: {fraud_rate:.4f} ({fraud_rate*100:.2f}%)")
# If extremely imbalanced, plan SMOTE / downsampling etc.
counts = df['is_fraud'].value_counts()
rates  = df['is_fraud'].value_counts(normalize=True)
print(pd.DataFrame({'count': counts, 'rate': rates}))

Fraud rate: 0.0058 (0.58%)
            count      rate
is_fraud
0         1289169  0.994211
1            7506  0.005789

# Why this matters
## Baseline “dumb” classifier

### A model that always predicts “not fraud” would be 99.42% accurate. That sounds better than it actually is since it never catches a single fraud. It would miss those cases of actual fraud causing loss. <br>


### Misleading accuracy
In imbalanced settings, accuracy is almost worthless. You need metrics that emphasize the minority (fraud) class. <br>


Choosing the right evaluation metrics <br>
Precision	Of all transactions flagged as fraud, what fraction truly were fraud? <br>
Recall	Of all actual frauds, what fraction did you catch? <br>
F1-Score	Harmonic mean of precision & recall; balances false positives & negatives. <br>
ROC-AUC	Model’s ability to rank fraud vs non-fraud across all thresholds. <br>
PR-AUC	Area under the Precision-Recall curve; more informative on imbalanced data. <br>

When training will have to split on the fraud column so that train/val/test all have the same fraud rate ~0.58%
This prevents model from seeing different fraud rates in each split. <br>

## Algorithmic Approaches <br>
### Class weights / Cost Sensitive Learning <br>
### -Tell the model that mistakes on fraud cost more than on normal transactions <br>
### -Anomaly detection which will test fraud as anomalies since train model will learn that normal transactions are not frauds (autoencoders) <br>

Note:
When fraud is rare, PR-AUC is often more meaningful than ROC-AUC, because PR-AUC focuses solely on performance for the positive (fraud) class.

# UPLOADING CLEANED DATA SET FOR PROCESSING + EDA TO USE

In [14]:
clean_path = '../../notebooks/1)Processing+EDA/credit_card_transactions_clean.csv'
df.to_csv(clean_path, index=False)
print("Cleaned data saved to", clean_path)

Cleaned data saved to ../../notebooks/1)Processing+EDA/credit_card_transactions_clean.csv